config/routes.rb
DefaultInit::Application.routes.draw do
  
  resources :habilities
  resources :user_habilities
  resources :postulations
  resources :actions
  resources :matures
  resources :matures
  resources :subcategories
  resources :categories
  resources :ideas
  resources :permissions
  resources :roles
  get 'auth/:provider/callback', to: 'sessions#create_with_oauth'  
  get 'auth/failure', to:  "home#index"

  get "admins/dashboard", to:  "admins#dashboard", as: 'admin_home'
  get "sessions/new"
  get "home/index"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "activate/:token" => "users#activate", :as => "activate"

  get "recover_pass" => "sessions#recover_pass", :as => "recover_pass"
  post "send_pass_recovery" => "sessions#send_pass_recovery", :as => "send_pass_recovery"
  get "change_password/:token" => "sessions#change_password", :as => "change_password"
  post "do_change_password" => "sessions#do_change_password", :as => "do_change_password"

  get "unsubscribe/:token" => "sessions#unsubscribe", :as => "unsubscribe"
  get "unsubscribe/:token/:from" => "sessions#unsubscribe", :as => "unsubscribe_from"
  get "contact" => "home#contact", :as => "contact"
  post "send_contact" => "home#send_contact", :as => "send_contact"

  resources :sessions
  resources :users

  get "main" => "main#index", :as => "main"
  get "home" => "home#index", :as => "home"
  root :to => "main#index"

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      resources :users
      get "/log_in" => "users#show"
      post "/log_in" => "users#show"
      post "/sign_up" => "users#create"
    end
  end

end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  before_action :set_subcategory, only: [:show, :edit, :update, :destroy]

  # GET /subcategories
  def index
    @subcategories = Subcategory.all
  end

  # GET /subcategories/1
  def show
  end

  # GET /subcategories/new
  def new
    @subcategory = Subcategory.new
  end

  # GET /subcategories/1/edit
  def edit
  end

  # POST /subcategories
  def create
    @subcategory = Subcategory.new(subcategory_params)

    if @subcategory.save
      redirect_to @subcategory, notice: 'Subcategory was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /subcategories/1
  def update
    if @subcategory.update(subcategory_params)
      redirect_to @subcategory, notice: 'Subcategory was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /subcategories/1
  def destroy
    @subcategory.destroy
    redirect_to subcategories_url, notice: 'Subcategory was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subcategory
      @subcategory = Subcategory.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def subcategory_params
      params.require(:subcategory).permit(:category_id, :name)
    end
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/views/subcategories/_form.html.haml
= form_for @subcategory do |f|
  - if @subcategory.errors.any?
    #error_explanation
      %h2= "#{pluralize(@subcategory.errors.count, "error")} prohibited this subcategory from being saved:"
      %ul
        - @subcategory.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :category_id
    = f.number_field :category_id
  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/subcategories/edit.html.haml
%h1 Editing subcategory

= render 'form'

= link_to 'Show', @subcategory
\|
= link_to 'Back', subcategories_path

app/views/subcategories/index.html.haml
%h1 Listing subcategories

%table
  %tr
    %th Category
    %th Name
    %th
    %th
    %th

  - @subcategories.each do |subcategory|
    %tr
      %td= subcategory.category_id
      %td= subcategory.name
      %td= link_to 'Show', subcategory
      %td= link_to 'Edit', edit_subcategory_path(subcategory)
      %td= link_to 'Destroy', subcategory, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Subcategory', new_subcategory_path

app/views/subcategories/new.html.haml
%h1 New subcategory

= render 'form'

= link_to 'Back', subcategories_path

app/views/subcategories/show.html.haml
%p#notice= notice

%p
  %b Category:
  = @subcategory.category_id
%p
  %b Name:
  = @subcategory.name

= link_to 'Edit', edit_subcategory_path(@subcategory)
\|
= link_to 'Back', subcategories_path