config/routes.rb
DefaultInit::Application.routes.draw do
  
  resources :habilities
  resources :user_habilities
  resources :postulations
  resources :actions
  resources :matures
  resources :matures
  resources :subcategories
  resources :categories
  resources :ideas
  resources :permissions
  resources :roles
  get 'auth/:provider/callback', to: 'sessions#create_with_oauth'  
  get 'auth/failure', to:  "home#index"

  get "admins/dashboard", to:  "admins#dashboard", as: 'admin_home'
  get "sessions/new"
  get "home/index"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "activate/:token" => "users#activate", :as => "activate"

  get "recover_pass" => "sessions#recover_pass", :as => "recover_pass"
  post "send_pass_recovery" => "sessions#send_pass_recovery", :as => "send_pass_recovery"
  get "change_password/:token" => "sessions#change_password", :as => "change_password"
  post "do_change_password" => "sessions#do_change_password", :as => "do_change_password"

  get "unsubscribe/:token" => "sessions#unsubscribe", :as => "unsubscribe"
  get "unsubscribe/:token/:from" => "sessions#unsubscribe", :as => "unsubscribe_from"
  get "contact" => "home#contact", :as => "contact"
  post "send_contact" => "home#send_contact", :as => "send_contact"

  resources :sessions
  resources :users

  get "main" => "main#index", :as => "main"
  get "home" => "home#index", :as => "home"
  root :to => "main#index"

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      resources :users
      get "/log_in" => "users#show"
      post "/log_in" => "users#show"
      post "/sign_up" => "users#create"
    end
  end

end

app/models/user_hability.rb
class UserHability < ActiveRecord::Base
end

app/controllers/user_habilities_controller.rb
class UserHabilitiesController < ApplicationController
  before_action :set_user_hability, only: [:show, :edit, :update, :destroy]

  # GET /user_habilities
  def index
    @user_habilities = UserHability.all
  end

  # GET /user_habilities/1
  def show
  end

  # GET /user_habilities/new
  def new
    @user_hability = UserHability.new
  end

  # GET /user_habilities/1/edit
  def edit
  end

  # POST /user_habilities
  def create
    @user_hability = UserHability.new(user_hability_params)

    if @user_hability.save
      redirect_to @user_hability, notice: 'User hability was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /user_habilities/1
  def update
    if @user_hability.update(user_hability_params)
      redirect_to @user_hability, notice: 'User hability was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /user_habilities/1
  def destroy
    @user_hability.destroy
    redirect_to user_habilities_url, notice: 'User hability was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_hability
      @user_hability = UserHability.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_hability_params
      params.require(:user_hability).permit(:user_id, :hability_id)
    end
end

app/helpers/user_habilities_helper.rb
module UserHabilitiesHelper
end

app/views/user_habilities/_form.html.haml
= form_for @user_hability do |f|
  - if @user_hability.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user_hability.errors.count, "error")} prohibited this user_hability from being saved:"
      %ul
        - @user_hability.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :hability_id
    = f.number_field :hability_id
  .actions
    = f.submit 'Save'

app/views/user_habilities/edit.html.haml
%h1 Editing user_hability

= render 'form'

= link_to 'Show', @user_hability
\|
= link_to 'Back', user_habilities_path

app/views/user_habilities/index.html.haml
%h1 Listing user_habilities

%table
  %tr
    %th User
    %th Hability
    %th
    %th
    %th

  - @user_habilities.each do |user_hability|
    %tr
      %td= user_hability.user_id
      %td= user_hability.hability_id
      %td= link_to 'Show', user_hability
      %td= link_to 'Edit', edit_user_hability_path(user_hability)
      %td= link_to 'Destroy', user_hability, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User hability', new_user_hability_path

app/views/user_habilities/new.html.haml
%h1 New user_hability

= render 'form'

= link_to 'Back', user_habilities_path

app/views/user_habilities/show.html.haml
%p#notice= notice

%p
  %b User:
  = @user_hability.user_id
%p
  %b Hability:
  = @user_hability.hability_id

= link_to 'Edit', edit_user_hability_path(@user_hability)
\|
= link_to 'Back', user_habilities_path