config/routes.rb
DefaultInit::Application.routes.draw do
  
  resources :habilities
  resources :user_habilities
  resources :postulations
  resources :actions
  resources :matures
  resources :matures
  resources :subcategories
  resources :categories
  resources :ideas
  resources :permissions
  resources :roles
  get 'auth/:provider/callback', to: 'sessions#create_with_oauth'  
  get 'auth/failure', to:  "home#index"

  get "admins/dashboard", to:  "admins#dashboard", as: 'admin_home'
  get "sessions/new"
  get "home/index"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "activate/:token" => "users#activate", :as => "activate"

  get "recover_pass" => "sessions#recover_pass", :as => "recover_pass"
  post "send_pass_recovery" => "sessions#send_pass_recovery", :as => "send_pass_recovery"
  get "change_password/:token" => "sessions#change_password", :as => "change_password"
  post "do_change_password" => "sessions#do_change_password", :as => "do_change_password"

  get "unsubscribe/:token" => "sessions#unsubscribe", :as => "unsubscribe"
  get "unsubscribe/:token/:from" => "sessions#unsubscribe", :as => "unsubscribe_from"
  get "contact" => "home#contact", :as => "contact"
  post "send_contact" => "home#send_contact", :as => "send_contact"

  resources :sessions
  resources :users

  get "main" => "main#index", :as => "main"
  get "home" => "home#index", :as => "home"
  root :to => "main#index"

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      resources :users
      get "/log_in" => "users#show"
      post "/log_in" => "users#show"
      post "/sign_up" => "users#create"
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new # guest user (not logged in)
    if user.admin?
        can :manage, :all
    else
        # global abilities
        can [:new, :create, :activate], User
        can [:index, :show], Blog

        # only if the user is logged in
        if user.id!=nil
            # can only update if its his own
            can [:show,:edit, :update], User, id: user.id
            can [:new, :edit, :create, :update, :destroy], Blog
            can [:new, :create, :destroy], Comment
        end
    end



    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/action.rb
class Action < ActiveRecord::Base
end

app/models/api_key.rb
class ApiKey < ActiveRecord::Base

	belongs_to :user

	before_create :generate_access_token

	def generate_access_token
	  begin
	    self.access_token = SecureRandom.hex
	  end while self.class.exists?(access_token: access_token)
	  begin
	    self.public_key = SecureRandom.hex
	  end while self.class.exists?(public_key: public_key)
	end
	
end

app/models/blacklist.rb
class Blacklist < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base

end

app/models/hability.rb
class Hability < ActiveRecord::Base
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_one :role
  has_many :permissions

end

app/models/mature.rb
class Mature < ActiveRecord::Base
end

app/models/permission.rb
class Permission < ActiveRecord::Base
  belongs_to :user
  belongs_to :idea
  belongs_to :role
end

app/models/postulation.rb
class Postulation < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :user
  has_one :idea
  has_many :permissions
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
end

app/models/token.rb
class Token < ActiveRecord::Base

	belongs_to :user

	before_create :generate
	def generate
		begin
			key = SecureRandom.hex
			key = key[(key.length/2)..(key.length-1)]
			key = key.gsub("/","").gsub(".","")
			self.value = key
		end while self.class.exists?(:value => key)
	end

end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :password, :current_password, :password_confirmation

  has_many :tokens
  has_many :user_oauths, dependent: :destroy
  has_and_belongs_to_many :ideas
  has_many :roles
  has_many :permissions

  before_save :encrypt_password
  #API
  has_one :api_key
  #END API
  validates_confirmation_of :password, :on => :create
  validates_presence_of :password, :on => :create
  validates_length_of :password, :minimum => 4, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email 
  # validates_presence_of :first_name
  # validates_presence_of :last_name

  has_attached_file :avatar, :styles => { :medium => "300x300>",  :medium_s => "300x300#", :thumb => "64x64#" },        
                     :storage => :s3,
                     :bucket => 'default-init', #crear nuevo bucket en amazon y cambiarlo
                     :s3_credentials => {
                        :access_key_id => ENV['S3_KEY_ID'],
                        :secret_access_key => ENV['S3_SECRET_ACCESS_KEY']
                     },
                     :path => ":attachment/:id/:style/:basename.:extension"

  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :finders]
  def slug_candidates
  [
    [:first_name, :last_name],
    [:first_name, :last_name, :id],
    [:first_name, :last_name, :id, :created_at_slug]
  ]
  end
  def created_at_slug
    I18n.l (self.created_at ? self.created_at : Time.now), format: :slug
  end

  def to_s
    r = (self.first_name ? self.first_name.to_s+' ' : '')+self.last_name.to_s
    return r!='' ? r : self.email
  end

  def full_name
    self.to_s
  end
  #API
  def to_json(scope = '')
    super(:only => [:id, :email], :methods => [:full_name, :access_token])
  end  
  def access_token
    self.api_key = self.api_key ? self.api_key : ApiKey.create(user_id: self.id)
    return self.api_key.access_token
  end
  #END API
  def name
    self.to_s
  end

  def admin?
    self.admin==true
  end

  def self.authenticate(email, password)
    user = find_by_email(email.downcase)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def valid_password?(password)
    self.password_hash == BCrypt::Engine.hash_secret(password, self.password_salt)
  end

  def encrypt_password
   if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def get_image(size = :medium)
    begin
      return self.avatar.url!='/avatars/original/missing.png' ? self.avatar(size) : self.image!=''&&self.image!=nil ? self.image : '/assets/missing.png'
    rescue
      return '/assets/missing.png'
    end
  end
  def has_image?
    return self.avatar.url!='/avatars/original/missing.png' 
  end
  #G+ login
  def self.from_omniauth(auth)
    u=UserOauth.find_by_provider_and_uid(auth["provider"], auth["uid"])
    u.present? ? u.user :  create_with_omniauth(auth)
  end
  def self.create_with_omniauth(auth)
    u=User.find_by_email(auth["info"]["email"])
    unless u
      create! do |user|
        user.email= auth["info"]["email"]
        user.password=SecureRandom.hex
        user.first_name = auth["info"]["first_name"]
        user.last_name = auth["info"]["last_name"]
        user.image = auth["info"]["image"] if auth["info"]["image"].present?
        u=user
      end
    end
    u.user_oauths.create(provider: auth["provider"],uid: auth["uid"])
    u
  end

end

app/models/user_oauth.rb
class UserOauth < ActiveRecord::Base
belongs_to :user
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/dashboard.html.haml
%h1 Admins#dashboard
%p Find me in app/views/admins/dashboard.html.haml

app/views/layouts/_footer.html.haml
%br
%br
%br
%br

%footer
  .footer_social
    .copy.col-sm-4.contFtr
      %p
        %strong=t('common.app_name')
        © copyright #{Time.now.year}. All rights reserved
    .other.col-sm-4.contFtr
      Otro
    .social.col-sm-4.contFtr
      %ul
        %li.google
          %a{href: '#'}
        %li.facebook
          %a{href: '#'}
        %li.twitter
          %a{href: '#'}
  %br
  %br
  %br
  %br

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    .clear
      %br
    %div{:class => "alert alert-#{name == 'notice' ? "success" : "danger"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%ul.nav.navbar-nav.btnMenu2int.right
	- unless current_user&&(can? :manage, :admin)&&['admins','users'].include?(controller.controller_name)
		- if current_user
			%li.imgUser.hidden-xs
				= image_tag current_user.get_image(:thumb), class: "img-circle"
			- if (can? :manage, :admin)
				%li.btnAdmin 
					= link_to t('common.nav.admin'), admin_home_path
			%li.btnNombre
				= link_to current_user.to_s, user_path(current_user)
			%li.btnsalir 
				= link_to t('common.nav.logout'), log_out_path
		- else
			%li.btnAdmin 
				= link_to t('common.nav.register'), sign_up_path, :class => 'register-btn'
			%li 
				= link_to 'Contacto', contact_path
			%li.btnAdmin
				= link_to t('common.nav.login'), log_in_path
			%li.btnsalir
				= link_to 'Salir'
	- else
		%li{:class => ['dashboard'].include?(controller.action_name) ? 'active' : ''}
			= link_to t('common.admin.dashboard'), admin_home_path
		%li{:class => 'index'==controller.action_name&&'users'==controller.controller_name ? 'active' : ''}
			= link_to t('common.admin.users'), users_path
		%li.btnNombre
			= link_to t('common.admin.go_back'), home_path
		%li.btnsalir
			= link_to 'Salir'

app/views/layouts/_slidemenu.html.haml
%ul.nav.navbar-nav.btnMenu2int
	- unless current_user&&(can? :manage, :admin)&&['admins','users'].include?(controller.controller_name)
		- if current_user
			%li.imgUser.hidden-xs
				= image_tag current_user.get_image(:thumb), class: "img-circle"
			- if (can? :manage, :admin)
				%li.btnAdmin 
					= link_to t('common.nav.admin'), admin_home_path
			%li.btnNombre
				= link_to current_user.to_s, user_path(current_user)
			%li.btnsalir 
				= link_to t('common.nav.logout'), log_out_path
		- else
			%li.btnAdmin 
				= link_to t('common.nav.register'), sign_up_path, :class => 'needs-login'
			%li.btnNombre 
				= link_to t('common.nav.login'), log_in_path, :class => 'needs-login'
			%li.btnsalir
				= link_to 'out'
	- else
		%li{:class => ['dashboard'].include?(controller.action_name) ? 'active' : ''}
			= link_to t('common.admin.dashboard'), admin_home_path
		%li{:class => 'index'==controller.action_name&&'users'==controller.controller_name ? 'active' : ''}
			= link_to t('common.admin.users'), users_path
		%li
			= link_to t('common.admin.go_back'), home_path
			

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      
      -# Favicon
        %link{:rel=>"icon", :type => "image/ico", :href => "/assets/favicon.ico"}
      
      %title= content_for?(:title) ? yield(:title) : t('common.app_name')
      %meta{:content => content_for?(:description) ? yield(:description) : t('common.app_desc'), :name => "description"}
      = metamagic
      = stylesheet_link_tag "application", :media => "all" #, "data-turbolinks-track" => true
      = javascript_include_tag "application" #, "data-turbolinks-track" => true
      = csrf_meta_tags
      = yield(:head)

      -# Mobile First
      %meta{name: "viewport", content:"width=device-width, initial-scale=1"}
      
      -# Google Analytics
        :javascript
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

          ga('create', 'UA-XXXXXX-X', 'dominio.cl');
          ga('send', 'pageview');

      -# Metatags para Facebook y Twitter
        %link{ :rel => "image_src",  :href => "/assets/logocuadrado.png" }
        %meta{ :property=>"og:image" , :content=>"/assets/logocuadrado.png" }
        %meta{ :property=>"og:type" , :content=>"company" }
        %meta{ :property=>"og:site_name" , :content=> t('common.app_name') }
        %meta{ :property=>"og:url" , :content=> t('common.app_url') }
        %meta{ :property=>"og:description",  :content=> t('common.app_desc') }
      
      -# Keywords para google y metatag de verificación de ownership
        %meta{  :name=>"keywords", :content=>"brainshots,brainshots.cl,ingenieria,tecnología,emprendimiento,chile" }
        %meta{ :name=>"google-site-verification", :content=>"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" }

  %body{:class => "#{controller_name} #{action_name}"}
    %header{:role => "banner"}
      .navbar-header

    .transition
      .marginMenu
        .slidemenu.visible-xs.alterHeight  
          = render 'layouts/slidemenu'

      .contGeneral.alterHeight    
        -unless @hide_header
          %header{:role => "banner"}
            .navbar-header
              %button.navbar-toggle.fa.fa-bars.visible-xs.slidemenu-trigger{ :type => "button"}
              %a.navbar-brand{:href => home_path}= t('common.app_name')
              %button.navbar-toggle.fa.fa-plus-square-o.btnPlus.visible-xs{"data-target" => ".bs-navbar-collapse", "data-toggle" => "collapse", :type => "button"}
              .nav.mainmenu.hidden-xs
                = render 'layouts/navigation'
        .visible-xs
          .marginMenu
          %nav.collapse.navbar-collapse.bs-navbar-collapse.menuExtra{:role => "navigation"}
            = render 'layouts/navigation'

        .container-fluid
          = render 'layouts/messages'
          -unless current_user
            = render partial: "sessions/register"
          = yield

      .hidden-xs
        = render 'layouts/footer'
    .visible-xs
      = render 'layouts/footer'

app/views/layouts/landing.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}

      -# Favicon
        %link{:rel=>"icon", :type => "image/ico", :href => "/assets/favicon.ico"}

      %title= content_for?(:title) ? yield(:title) : t('common.app_name')
      %meta{:content => content_for?(:description) ? yield(:description) : t('common.app_desc'), :name => "description"}
      %meta{:name=>"viewport", :content=>"width=device-width, initial-scale=1, maximum-scale=1"}
      = metamagic
      = stylesheet_link_tag "application", :media => "all" #, "data-turbolinks-track" => true
      = javascript_include_tag "application" #, "data-turbolinks-track" => true
      = csrf_meta_tags
      = yield(:head)

      -# Mobile First
      %meta{name: "viewport", content:"width=device-width, initial-scale=1"}

  -# Google Analytics
        :javascript
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

          ga('create', 'UA-XXXXXX-X', 'dominio.cl');
          ga('send', 'pageview');

  -# Metatags para Facebook y Twitter
        %link{ :rel => "image_src",  :href => "/assets/logocuadrado.png" }
        %meta{ :property=>"og:image" , :content=>"/assets/logocuadrado.png" }
        %meta{ :property=>"og:type" , :content=>"company" }
        %meta{ :property=>"og:site_name" , :content=> t('common.app_name') }
        %meta{ :property=>"og:url" , :content=> t('common.app_url') }
        %meta{ :property=>"og:description",  :content=> t('common.app_desc') }

  -# Keywords para google y metatag de verificación de ownership
        %meta{  :name=>"keywords", :content=>"brainshots,brainshots.cl,ingenieria,tecnología,emprendimiento,chile" }
        %meta{ :name=>"google-site-verification", :content=>"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" }

  %body{:class => "#{controller_name} #{action_name}"}
    %header{:role => "banner"}
      .navbar-header

    .transition
      .marginMenu
        .slidemenu.visible-xs.alterHeight
          = render 'layouts/slidemenu'

      .contGeneral.alterHeight
        -unless @hide_header
          %header{:role => "banner"}
            .navbar-header
              %button.navbar-toggle.fa.fa-bars.visible-xs.slidemenu-trigger{ :type => "button"}
              %a.navbar-brand{:href => home_path}= t('common.app_name')
              %button.navbar-toggle.fa.fa-plus-square-o.btnPlus.visible-xs{"data-target" => ".bs-navbar-collapse", "data-toggle" => "collapse", :type => "button"}
              .nav.mainmenu.hidden-xs
                = render 'layouts/navigation'
        .visible-xs
          .marginMenu
          %nav.collapse.navbar-collapse.bs-navbar-collapse.menuExtra{:role => "navigation"}
            = render 'layouts/navigation'


        = render 'layouts/messages'
        -unless current_user
          = render partial: "sessions/register"
        = yield
      .hidden-xs
        = render 'layouts/footer'
    .visible-xs
      = render 'layouts/footer'